# Generated by Django 4.0.10 on 2023-04-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_administrativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativo',
            options={'permissions': (('acessar_funcionarios_administrativos', 'Acessar Funcionários Administrativos'),), 'verbose_name': 'Administrativo', 'verbose_name_plural': 'Administrativos'},
        ),
    ]
