# Generated by Django 4.0.10 on 2023-04-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funcionarios.funcionario')),
                ('crmv', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='CRMV')),
            ],
            options={
                'verbose_name': 'Veterinário',
                'verbose_name_plural': 'Veterinários',
                'permissions': (('acessar_veterinarios', 'Acessar Veterinários'),),
            },
            bases=('funcionarios.funcionario',),
        ),
    ]
