# Generated by Django 4.0.10 on 2023-05-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_alter_dependente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependentes_do_funcionario', to='funcionarios.administrativo', verbose_name='Funcionario'),
        ),
    ]
