# Generated by Django 4.0.10 on 2023-04-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'permissions': (('acessar_consultas', 'Acessar Consultas'),), 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
