# Generated by Django 4.0.10 on 2023-04-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data_da_consulta'], 'permissions': (('acessar_consultas', 'Acessar Consultas'),), 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
