from .administrativo_serializer import AdministrativoSerializer, AdministrativoLookupSerializer, AdministrativoCreateSerializer
from .veterinario_serializer import VeterinarioSerializer, VeterinarioHistoricoDeConsultasSerializser
from .dependente_serializer import DependenteSerializer, DependenteCreateSerializer
