# Generated by Django 4.0.10 on 2023-03-11 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0005_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cnpj', models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='CNPJ')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], default='FEMININO', max_length=50, verbose_name='Sexo')),
                ('tipo_logradouro', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Tipo de Logradouro')),
                ('logradouro', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Logradouro')),
                ('bairro', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Bairro')),
                ('numero', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='CEP')),
                ('ddd', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='DDD')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone')),
                ('ddd_segundo_telefone', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='DDD')),
                ('segundo_telefone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='E-mail')),
                ('paciente', models.ManyToManyField(blank=True, related_name='tutores_do_paciente', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
