# Generated by Django 4.0.10 on 2023-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_cnpj_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], default='FEMININO', max_length=50, null=True, verbose_name='Sexo'),
        ),
    ]
