# Generated by Django 4.0.10 on 2023-03-04 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_porte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sexo', models.CharField(choices=[('MACHO', 'Macho'), ('FEMEA', 'Fêmea')], default='FEMEA', max_length=50, verbose_name='Sexo')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de nascimento aproximada')),
                ('pelagem', models.CharField(blank=True, default='', max_length=100, verbose_name='Pelagem')),
                ('cor', models.CharField(blank=True, default='', max_length=100, verbose_name='Cor')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_da_especie', to='pacientes.especie')),
                ('porte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_do_porte', to='pacientes.porte')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_da_raca', to='pacientes.raca')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
