# Generated by Django 4.0.10 on 2023-03-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_cnpj_cliente_cpf'),
        ('pacientes', '0005_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_do_cliente', to='clientes.cliente', verbose_name='Tutor'),
        ),
    ]
