# Generated by Django 4.0.10 on 2023-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20230408_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MACHO', 'Macho'), ('FEMEA', 'Fêmea')], default='FEMEA', max_length=50, null=True, verbose_name='Sexo'),
        ),
    ]
