# Generated by Django 4.0.10 on 2023-04-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cor',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_da_especie', to='pacientes.especie'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pelagem',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Pelagem'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='porte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_do_porte', to='pacientes.porte'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_da_raca', to='pacientes.raca'),
        ),
    ]
