# Generated by Django 4.0.10 on 2023-04-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_sexo'),
        ('pacientes', '0011_alter_paciente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_do_cliente', to='clientes.cliente', verbose_name='Tutor'),
        ),
    ]
